### ISSUE TITLE
[FEAT] Programmatically reset the input boxes?

### ISSUE THREAD

**Issue by minnieoo** [aclist/kbin-kes#124]
**Is your feature request related to a problem? Please describe.**
I am facing an issue with programmatically resetting input values and triggering the 'input' event. In my script, I have number inputs and a button that's purpose is to reset those values. I can insert the desired value programmatically, but it does not have the desired effect. It only inserts the value visually but doesn't actually change the value itself, unless I manually click the arrow up or down buttons on the number input. If I don't, they go back to whatever they were before I clicked the reset button upon closing and reopening the modal. 

**Describe the solution you'd like**
I would like to be able to programmatically reset the input values and trigger the 'input' event in order to update the corresponding elements and achieve the desired behavior. The values are being changed programmatically, but the elements do not change accordingly. 

Only viable solution I could think of is to import the codebase where updateState is.

**Describe alternatives you've considered**
MVP
`document.querySelector("body > div.kes-settings-modal > div > div.kes-settings-modal-content > div.kes-settings-modal-helpbox > input[type=number]:nth-child(10)").value = 30
document.querySelector('.kes-settings-modal-helpbox').dispatchEvent(new Event('input'))`
and
`updateState(element)`
and more that I don't remember now

My script: https://github.com/minnieoo/kbin-kes/blob/testing/mods/resize-text.user.js

**Additional context**

https://github.com/aclist/kbin-kes/assets/137783738/a8b14229-125f-4467-83cf-46ecc51e3335

Scripts functionality, notice how the elements do not change when programmatically reset:
https://github.com/aclist/kbin-kes/assets/137783738/3fdac58a-0926-4bd4-937f-fbab72de7084

The code that does this:
```
if (!eventListenerDefaultButton) {
    eventListenerDefaultButton = (e) => {
      const defaultButton = document.querySelector('input[kes-key="defaultButton"]'); //button
      const buttonColor = defaultButton.style.backgroundColor;
      function buttonStyle(button) {
        button.style.backgroundColor = buttonColor;
      }
  
      if (e.target.type === 'button' && e.target.getAttribute('kes-key') === 'defaultButton') {
        console.log('Reset defaults button clicked');
        defaultButton.style.backgroundColor = '#079D0C'
        setTimeout(() => buttonStyle(defaultButton), 500);
  
        const numSelectMain = document.querySelectorAll('input[kes-key^="option"]');
  
        numSelectMain.forEach(numSelectElem => {
          numSelectElem.setAttribute("value", "12");
          numSelectElem.value = "12";
          updateState(numSelectElem) // Trigger input event to update CSS (doesn't work)
  
          // Apply updated font size to the corresponding element
          const optionKey = numSelectElem.getAttribute('kes-key');
          const elementToUpdate = document.querySelector(`[kes-key="${optionKey}"]`);
          if (elementToUpdate) {
            elementToUpdate.style.fontSize = fontSizes[optionKey];
          }
        });
  
        Object.keys(fontSizes).forEach(key => {
          console.log(key + ': ' + fontSizes[key])
          fontSizes[key] = '12px';
          console.log(`UPDATED: ${key}: ${fontSizes[key]}`)
        });
      }
    }
  
    document.addEventListener('click', eventListenerDefaultButton); 
 }

```

The way I have been testing my script is through using this on tampermonkey, it just changes some links to update with my branch:
https://gist.github.com/minnieoo/b5ea8c5480b1065854faabf026e3c63f

**Comment by aclist** [comment]
Thanks for all the details and video, this is great.

A couple of things:

IIRC, the reset specification as far as forms are concerned actually behaves this way on any field if you try it on other sites. That is, it just updates the content of the input area but doesn't apply any changes per se. So it sounds like we need to be more clever here about capturing these events and then applying the reset, not just to the form. 

My initial thought is that the reset should be bound to an action that sets the state of fields to `initial` as defined in the manifest and then calls `updateState()`. You wouldn't have to add any special logic in the mod, the reset button would just by design reset everything to the initial value and propagate the changes. Does this sound good?

I don't think the mods trying to reach into the helpbox to query stuff is the right way to go about it.

Another thing that may interest you is Transparent Mode. Looks like you are on RC 27, so pull the latest version and you should see a new icon on the menu that blanks the window. Not sure if this fits your use case, but give it a try.

**Comment by aclist** [comment]
To clarify, when I said "sets the state of fields to initial," I mean actually reverting their values in the localStorage to the initial values and then applying the contents of localStorage back through the page. This would be the most conformant way of respecting the KES framework, so sounds like we need to extend support for the reset button.

**Comment by aclist** [comment]
What I have worked up so far:

1. Reset buttons added to the helpbox through the manifest are bound to a click event
2. The manifest adds a new key called `catch_reset`, which is an array
3. In the array, define the key names you want to trigger on reset, e.g.:
```
"catch_reset": [
   "optionCreate",
   "optionSidebar"
]
```
4. In the event the button is pressed, iterate over the keys above and update their value in localStorage to the `initial` value
5. Also visually update the contents of their input fields to the initial value
6. Propagate the changes
7. For now, limit to one reset button per mod 

Sounds good? I think this should entirely obviate the need for a mod to hijack the helpbox and poll it by itself.

**Comment by aclist** [comment]
Hi @minnieoo, the latest version (RC 44) contains an update to both the number and reset fields functionality so that numbers visually update correctly and into the stored settings, and when clicking a reset button, it will repopulate all specified input fields to their initial value and update their state. I didn't test if it will apply those changes immediately, but if it's not, we just need to add a single line.

There is an example mod in `manifest.json` called Catch Reset Test (last mod in the file), and it's located on the Debug page of the sidebar as the last mod. This should explain everything you need to request the same field, and you don't need to poll it yourself in your code.

As for your code not reverting changes unless the page reloads, I think that's a simple enough fix: rather than setting the font size via the attributes, apply it via the CSS `font-size` property; when toggling off, just set the `font-size` of those fields to `initial` and they should revert to whatever the page set.

**Comment by aclist** [comment]
Added in https://github.com/aclist/kbin-kes/releases/tag/2.0.0-rc.44

**Comment by minnieoo** [comment]
@aclist YOU'RE INCREDIBLE! This totally fixed it, and made everything super easy for me! I am very grateful for your hard work and patience, thank you! I followed your advice about using the font-size property as well, thanks for the tip as well.

About transparency, I see the new icon and it works nicely! For the toggle I had, I found it convenient because I could actively change the font-size and see the changes at the same time, which I did to avoid having to re-enter (or unhide) the modal and access the number inputs, which I still have to do with the new transparency icon whether it be by re-entering with the tool icon or clicking anywhere on screen, I still have to go back and forth to see what changes I made and then make more changes. It's a small inconvenience that is probably very specific to my script, for me my transparency toggle was convenient at the time while I was changing the numbers every few minutes and wanted to eliminate the extra clicking (change, look, change look, repeat x100). But, I don't think people who aren't changing the font sizes near as much as I have had to for testing purposes will even mind, so I will remove my toggle before I make the PR. The transparency is a very nice and clever addition.

I want to say thanks again for this fix! This threw me for a loop and I spent an embarrassingly long amount of time trying to get around it. I didn't know that the reset stuff behaves this way by default. I am learning a hell of a lot making this script and with your help lol 💜🍻

**Comment by aclist** [comment]
> This totally fixed it, and made everything super easy for me! I am very grateful for your hard work and patience, thank you! 

Yeah, I think it should be as close to "no-code" in terms of setting up the menu as possible, so the mod authors can just request stuff and don't have to try to recursively poll the state of the input elements or set up extra listeners. It was pretty straightforward thanks to the great details you provided, and this feature was clearly lacking once I saw what you were talking about.

> I followed your advice about using the font-size property as well, thanks for the tip as well.

No problem!

> For the toggle I had, I found it convenient because I could actively change the font-size and see the changes at the same time, which I did to avoid having to re-enter (or unhide) the modal and access the number inputs, which I still have to do with the new transparency icon whether it be by re-entering with the tool icon or clicking anywhere on screen, I still have to go back and forth to see what changes I made and then make more changes. 

Yeah, I totally agreed, I figured you would find this to not be ideal for your situation, since you need to constantly increment the value and see the changes live, so it doesn't make sense to turn on and off repeatedly. But I figured you should take a look at it just in case.

> so I will remove my toggle before I make the PR.

No need, I can see the case for it. It's fine if specific mods have some escape hatches to do what they need to do, provided it's not destructive.

> The transparency is a very nice and clever addition.

I'm very happy with that, can't believe we didn't think of it sooner.

> This threw me for a loop and I spent an embarrassingly long amount of time trying to get around it.

Before getting stuck in a loop, feel free to call out for help before the problem gets more complicated.

> I didn't know that the reset stuff behaves this way by default.

Well, it's a bit of a mixed bag: by default a field is just "dumb" and you increment some value, and then click a Submit button or something and it takes the current value and sends it somewhere, then resets the form, so the value currently displayed in the field isn't necessarily always updating the field's own internal value. There is the currently displayed value and the internal value. For our purposes, we wanted to do both, update the internal value inside the element so KES can grab it when updating, but also visually reset it and make it respond to changes. So this was something lacking on the KES side for sure. 

I'm looking forward to seeing the final creation.
