### ISSUE TITLE
[BUG] KES doesnt work with Firemonkey

### ISSUE THREAD

**Issue by sterno900** [aclist/kbin-kes#187]
Using Firemonkey on Librewolf
The Wrench icon does not appear and the shortcut CTRL-SHIFT-? dont work either.

- KES version 2.0.7

- Extension: FireMonkey 2.72

 - Windows 10 Pro 22h2
 
 - Librewolf   115.0.2-2

**Comment by aclist** [comment]
Thanks for the report. In basic control tests, I am unable to even get FireMonkey to function correctly with vanilla Firefox when using barebones tests like printing a message to the dev console. Unfortunately, there seems to be no dedicated API documentation for this extension provided by the developer. It also seems to implement the GM API differently from all other extensions. I will continue trying to get it working, but thus far I am not able to set up a basic environment that would even allow testing it with KES. 

Depending on the outcome, we may have to list this extension as unsupported due to the total lack of formal documentation. Quite a lot of work has gone into ensuring cross-compatibility between the major *monkey extensions by complying with their API specification, but if FireMonkey is doing its own thing, it may be difficult to support unless writing custom logic for it.

This is not to say the outcome is invalid yet, but currently I'm at an impasse with it and will keep troubleshooting before reporting back.

**Comment by aclist** [comment]
Thank you for finding that. I'll be testing it again in more detail with this information.

**Comment by aclist** [comment]
This has been fixed and will be going into the `2.1.2` hotfix releasing later today. (Currently on `2.1.1`).

**Comment by aclist** [comment]
This should be live and fixed now, please check.

**Comment by aclist** [comment]
Alright, great. Thanks for providing the info needed to track this down and resolve it.
