### ISSUE TITLE
[CHORE] Accessibility

### ISSUE THREAD

**Issue by aclist** [aclist/kbin-kes#189]
@minnieoo 

Some ideas. Cf. https://developer.mozilla.org/en-US/docs/Learn/Accessibility/What_is_accessibility

### Visual impairment
   - Colorblindness
      -  Do not use typically green/red colors for binary choices, allow customization of colors
- Using screen readers
   - Elements should have `alt` text, and/or `aria label` attributes
- Low vision
   - Needing high visibility/contrast
   - Strong separation between elements, photonegative

### Mobility impairment
- Input
   -  Support both mouse and hotkeys

### Auditory impairment
- Probably doesn't apply

### Mobile devices
- Responsive design
- Elements large enough to tap

### Limited bandwidth/data caps
- Performance
- Reduce size of loaded elements
- Cache content

**Comment by minnieoo** [comment]
oh wow this is great! something i also discovered that caught my eye was a hover indicator, which i also found when researching accessibility features. it seemed easy enough to implement so I have started with that. this is what i have so far, it's pretty rudimentary, not perfect, but I feel like i am 95% of the way there besides tweaking


https://github.com/aclist/kbin-kes/assets/137783738/2c260215-a79d-42b5-b239-4cd8192a20ec



i tried to be more efficient with the code this time and it is significantly shorter than it started out being (originally had loops and pasted the loops, then i remembered you said if it is being written more than once, it doesn't need to be :D), so i am happy about that. this is just a test version in tampermonkey btw

```js

    const selectors = 'a:hover, h1:hover, h2:hover, h3:hover, h4:hover, h5:hover, h6:hover, img:hover, button:hover, label:hover, markdown-toolbar:hover, textarea:hover, i:hover, time:hover, small:hover, div.content:hover, ul:hover, li:hover, span:hover, figure:hover';
    const styleElement = document.createElement('style');
    const outline = `${selectors} { outline: 2px solid blue;}`;
    const border = 'p:not(div.content p):hover { border: 2px solid blue;}';
    styleElement.innerText = outline + border;
    document.head.appendChild(styleElement);

```

what do you think so far? btw the reason i chose border instead of outline for p is because the outline was getting cut off on the top and bottom usually with p elements. i guess they overlapped, so it wasn't very clear what I was hovering on, which is the entire goal lol. i did originally use '*' as a selector but that was a whole mess, it's easier imo to select what i need than to go around deselecting what i don't, unless im wrong. but yea

**Comment by minnieoo** [comment]
so far:

https://github.com/aclist/kbin-kes/assets/137783738/0fe9bc0b-d504-4911-b01e-a2b8f4674e88



[code here](https://github.com/minnieoo/kbin-kes/blob/hover/mods/hover-indicator.user.js)

**Comment by aclist** [comment]
Seems pretty great and looks already done. I could see that being useful for vision issues.

Speaking of repetition, here's my suggestion for code cleanliness:
```
const sels = [
    "a",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "img",
    "button",
    "label",
    "markdown-toolbar",
    "textarea",
    "i",
    "time",
    "small",
    "div.content",
    "ul",
    "li",
    "span",
    "figure"
]

const selectors = sels.join(':hover, ');
const outline = `${selectors} { outline: 2px solid blue;}`;

```

Storing the items linewise in an array is IMO easier to read/maintain, rather than a super long line (and generally it's frowned upon to go beyond 80-100 chars per line for compatibility reasons). You can also keep the delimiter outside of the selector names and just concat them with a `:hover, ` so that the selectors are stored by themselves. 

>  i did originally use '*' as a selector but that was a whole mess, it's easier imo to select what i need than to go around deselecting what i don't, unless im wrong. but yea

I agree, I actually tested it out of curiosity and it was insanity

**Comment by minnieoo** [comment]
oh that looks much better! thank you :D
