### ISSUE TITLE
[BUG] Contents of settings modal not showing

### ISSUE THREAD

**Issue by alexander-paterson** [aclist/kbin-kes#205]
**Describe the bug**
When I click the settings button, I'm not seeing the settings window/modal, I'm seeing markup.

**To Reproduce**
1. Click the settings button.

**Expected behavior**
The settings should open.

**Screenshots**
![image](https://github.com/aclist/kbin-kes/assets/931083/38e08a60-bfc0-4eb9-bcba-28aaa2237cc9)

**KES version:**
- Version number 2.1.4

**Extension and version:**
- Extension: ViolentMonkey
- Version number: v2.15.0

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Browser version 116.0

**Comment by aclist** [comment]
I cannot reproduce this yet. Have you tried removing KES and reinstalling it from scratch?

**Comment by aclist** [comment]
I took a look at changes in the code between 2.1.3 and 2.1.4, and the only thing that changed was the format of a URL used in two add-ons to make them support domains other than kbin.social, so that change would not have caused the above behavior. My current hypothesis is that the style data became truncated for some reason while downloading the update.

Were there any other errors in the dev console?

**Comment by aclist** [comment]
I was able to get this bug to occur once, but I haven't found steps for reliably reproducing it yet.

**Comment by aclist** [comment]
A few questions:

1. Did you have multiple extensions installed, such as Tampermonkey/Violentmonkey/Greasemonkey at the same time?
2. Did your computer or Firefox crash at any time while it was open and before this error occurred?

**Comment by alexander-paterson** [comment]
1. No, just ViolentMonkey
2. I don't recall anything crashing.

It hasn't happened again after removing and re-adding the script.

**Comment by aclist** [comment]
I have encountered this only once during the intervening three months since you posted it. I confirm that this bug exists, but it is difficult to reliably reproduce, as it seems to be either a race condition or related to throttling from GitHub's API. My surmises are that something fails when pulling in the remote resources, and so the widget inserts the paths to the CSS without actually loading it. I think it might be possible to reproduce this on an initial reinstall, but I have had trouble getting it to happen with 100% reliability. I will continue investigating the root cause.

**Comment by Pamasich** [comment]
I've had this issue too months ago and decided to quickly look into it today.

You can actually reliably reproduce this by changing the "raw/" in `branchPath` to "blob/".

For some reason, when looking up the version file to check for a new version, Github returns the wrong page when this issue occurs. Instead of the raw page with just the file contents, the regular page with all the Github HTML is returned. Which is then inserted into the version field, resulting in the mess in OP's screenshot.

This used to happen pretty frequently for me around when this issue was reported here, but I haven't seen it since. So this might have been a bug Github fixed. But in case it happens again, hopefully this can help with fixing it.

**Comment by aclist** [comment]
I think it relates to Github's redirect logic: rather than using the github.com URL as a variable interpolated for both user-facing pages and raw files, and allowing Github to redirect when the path includes `/raw`, it'd be more robust for us to specify the `raw.githubusercontent.com` domain explicitly so that fetching the `user.css` comes directly from the intended URL without extraneous redirects in between.
