### ISSUE TITLE
[BUG] OP label color inaccuracy

### ISSUE THREAD

**Issue by Coolie2** [aclist/kbin-kes#220]
**Describe the bug**
The OP label colors indicate the color of the label when the mouse hovers over the comment in question, rather than the label's standard color. For instance, to make the foreground color match the grey of the OP commenter's username, the color has to be set to 96/96/96, the color the the username when highlighted, rather than 136/136/136, the color of the username otherwise.

**To Reproduce**
1. Set the foreground or background color of the OP label to a defined value.
2. Using a high DPI monitor or a high level of zoom in one's browser, use a color picking tool to see the color of the OP label when not highlighted by the mouse. As browser-based extensions seem to have difficulty registering the color without also highlighting the comment in the process, the most reliable means of doing so seems to be to take a screenshot and subsequently using a utility such as GIMP to register the color. In the case of 96/96/96, the displayed color is 136/136/136.

**Expected behavior**
The OP label's defined colors should correspond to the colors that are displayed when the comment in question is not highlighted.

**Screenshots**
While the default color for usernames on Kbin is 136/136/136, entering this value for the OP label foreground text makes it appear too bright:

<img width="176" alt="Example1" src="https://github.com/aclist/kbin-kes/assets/36297934/e82043a5-aae2-4ac5-9b9f-2ef230e7be8b">

Taking the same screenshot when the comment is highlighted, the OP label is still brighter than the highlighted username color, but matches the initial username color:

<img width="175" alt="Example2" src="https://github.com/aclist/kbin-kes/assets/36297934/9d32b106-cebb-4919-a52d-73175cde531f">

By instead entering the color of a highlighted username, the darker 96/96/96, the colors now match:

<img width="185" alt="Example3" src="https://github.com/aclist/kbin-kes/assets/36297934/944bed46-a7b0-4c42-aa6a-4cd9c97f7ba7">

[When submitting a bug report, you can click the clipboard icon on the bottom right of the KES menu to copy system settings to the clipboard. Alternatively, you can manually enter that information below.]

**KES version:**
- Version number: 2.2.2

**Extension and version:**
- Extension: Tampermonkey
- Version number: 4.19.0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Browser version: 118.0.5993.89

**Comment by aclist** [comment]
Thank you for waiting. After investigating this further, I think it might be contraindicated to forcibly change the opacity of elements in the header. The reason is because the header is designed to have a 75% opacity under kbin's default theming, and only return to 100% opacity on a hover action. Insofar as the OP label is being put into the header, I believe it should respect the default styling of the header rather than overriding it, since that behavior would be unexpected. I don't think we should intentionally change styling if it affects other default elements, since the outcome would be unexpected and deviate from the basic kbin theme.

As a compromise, I think we could include a disclaimer in the add-on's description indicating that the colors will be reduced to 75% opacity when inserted into the header. Does this seem reasonable?

We could also try visualizing what the reduced opacity will look like, but it would be unorthodox to make a special case for this one add-on, since by design KES add-ons should draw from common widgets (in this case, the colorpicker) when building the settings panel.

**Comment by Coolie2** [comment]
I guess a disclaimer would at least tell people why the colors appear as they do in case anyone else runs into the same issue.
