### ISSUE TITLE
[FEAT] Allow "grey circle with number" look for the Notifications panel icon

### ISSUE THREAD

**Issue by aaronliu0130** [aclist/kbin-kes#232]
**Is your feature request related to a problem? Please describe.**
Kbin never uses red across the entire site. The top bar looks very passive, yet when I have a new notification the notifications panel will have a red thing.

**Describe the solution you'd like**
Allow me to use the original new notification look, a grey circle with a number inside it, to replace the bell icon.

**Describe alternatives you've considered**
Only replace the red color with grey. That's better, but still feels weird to me...

**Comment by aclist** [comment]
KES does not hardcode any colors of its own choosing. All colors used are sourced from Kbin's own internal theming for the user's currently chosen theme. While the red notification color is seldom seen on the site, it is in fact a color used by Kbin that is specified for alerts and notifications, and may appear as a color other than red depending on which theme the user loaded. 

This styling was also chosen to distinguish the notipanel's notifications from other general notifications.

What we could do here is add a colorpicker to the mod's settings page so that the user can set their own preferred color.

**Comment by aaronliu0130** [comment]
Hmm, well I was proposing a choice for having the entire thing look like this:
![image](https://github.com/aclist/kbin-kes/assets/11874211/462be932-6711-4f62-8108-57e328b197c0)

What alerts and notifications exist?

**Comment by aclist** [comment]
I am not the author of the original notifications panel mod. If I recall correctly, by default Kbin tries to separate the message count from the in-thread reply count, and the fundamental purpose of the notifications panel is to:

- Hide the default Kbin count
- Combine the sum of these notifications into a single count in one panel
- Display the combined count with the panel button

I don't think that specification will change further, as it was already complex to combine these disparate requirements into one. The best we can do is provide a colorpicker to change the bell notifications color to  one you find pleasing.

I do not know the full extent of alerts and notifications Kbin chooses to use from time to time. We are just complying with the Kbin specifications for forwards compatibility. KES never defines its own colors or theming.

**Comment by aclist** [comment]
As a follow-up to your question, I have investigated the original design of the add-on and how notification badges work. It appears that Kbin defines a series of "badges" used to indicate circular alert widgets on the page. These badges inherit a specific classname and are bound to specific colors determined by Kbin. The notification panel simply uses the badge format set by Kbin and does not dictate the color, since it is bound to that badge type. We could look into using a different badge type, but I believe the badge types are somewhat limited.
