### ISSUE TITLE
[MOD] Allow expanding text in posts outside of per-thread view

### ISSUE THREAD

**Issue by aaronliu0130** [aclist/kbin-kes#233]
**Is this request to port an existing userscript or mod, or create a new one?**
New one, unless this has already been created

**Describe the solution you'd like**
Certain posts have some text. Currently, on pages like the homepage, only the first few lines of text are shown. I'd like a way to expand text just like photos and certain embeds expand when I click on the photo button

https://github.com/danielpervan/Kbin-Usability-Pack had this feature, but it's gone unmaintained

**Comment by aclist** [comment]
Working prototype is complete, will enter testing branch next week and go into stable branch after further testing.

Sample images follow:
BEFORE EXPANSION
![1702686884](https://github.com/aclist/kbin-kes/assets/92275929/8e83c273-d1e1-4004-a8b0-d2aee079ca70)

AFTER EXPANSION
![1702686893](https://github.com/aclist/kbin-kes/assets/92275929/1d18ec0e-b850-4812-b882-277d02db08ce)



Note that post body text is not contained on the thread index, so it has to be fetched and loaded on demand when the EXPAND button is clicked. This may take a few moments to load in the background while the contents are retrieved.

**Comment by aaronliu0130** [comment]
I was thinking maybe make the little ![ärticle" (newspaper)](https://github.com/aclist/kbin-kes/assets/11874211/91eed803-8f83-4166-be25-f68f5d8d53eb) icon be the expand button as having a blue in a bunch of grey stands out quite a bit

**Comment by aclist** [comment]
I don't think it is a good idea to mix native features with KES features, or to agglomerate two features into one, as it is liable to lead to confusion. Also, some posts do not come with the expand photo icon because they are not image posts. I already feel that this mod is overengineered as it is, since we have to load additional remote content every time the button is clicked, so I don't think the specifications should be changed here for the sake of cosmetic concerns.

As for standing out, visibility of links is important for accessibility purposes. It may look unpleasant to you, but could be helpful for those with screen readers or low vision issues. Mods should be designed with the maximum number of users in mind. If you don't like the appearance, you are welcome to apply additional CSS styling in your browser.

**Comment by aaronliu0130** [comment]
Well, maybe it could be lowercase at least?

**Comment by aclist** [comment]
I have made a few changes so that the button does not occlude the text as much and so that it is placed on its own line away from the body text. The label switches from Expand/Loading/Collapse depending on the context.

If you are curious, this feature is now available in the [testing branch](https://github.com/aclist/kbin-kes/raw/testing/kes.user.js). The add-on is called `Expand post text in thread index` available in the `Threads` page.

Note that the testing branch may introduce breaking changes from time to time, so after testing this feature, you can go back to the [stable branch](https://github.com/aclist/kbin-kes/raw/main/kes.user.js). The finalized version will make its way into version 3.2.0.

**Comment by aclist** [comment]
Resolved in 3.2.0

**Comment by aaronliu0130** [comment]
Is it really needed to have the "EXPAND" and "COLLAPSE" buttons in all-caps? Also, both buttons disappear after you click "COLLAPSE".

**Comment by aclist** [comment]
> Also, both buttons disappear after you click "COLLAPSE".

Sorry about that, this bug somehow slipped past in testing. I have fixed it and will update the new version soon. As for the appearance, I am sorry that it is not exactly to your liking, but maybe we can make it look more like a button in the future. It is a low priority (focus is on adding nonexistent features to kbin over styling). It is caps for now to distinguish it from the rest of the text.

**Comment by aaronliu0130** [comment]
Thanks for the fix. Well, food for thought are such settings and maybe removing the excess new lines this seems to generate?
![image](https://github.com/aclist/kbin-kes/assets/11874211/a6fbb5f7-70ec-40fa-90b8-ddcf7e9a3462)
![image](https://github.com/aclist/kbin-kes/assets/11874211/17613af9-5b88-447e-9567-24af2a59ed6e)

**Comment by aclist** [comment]
It looks like the body of the posts themselves comes with an additional line break when it's fetched from the server. We can scrub the last line break so that it doesn't get pushed down. This will go into the next update, no immediate hotfix.

**Comment by aaronliu0130** [comment]
Same thing with the extra linebreak at the top?

**Comment by aclist** [comment]
The remote inserts line breaks into the content at random, some are legitimate, some are not. I am not sure of the entire syntax.

**Comment by aaronliu0130** [comment]
We could remove the opening and ending linebreak for a start.

**Comment by aaronliu0130** [comment]
Also, just lowercasing the link buttons isn't even CSS. Lowercasing makes it have the same level of distinction against Kbin elements without making it shout at you.

**Comment by aclist** [comment]
Resolved in 3.2.3

- Fixed extraneous newlines being inserted before and after text body
- Added ability to set custom text labels for expand/collapse/loading states
