### ISSUE TITLE
[BUG] Unblur NSFW thumbnails not working on fedia.io

### ISSUE THREAD

**Issue by NaturalHate** [aclist/kbin-kes#239]
**Describe the bug**
As per the title, unbluring NSFW thumbnails does not work on said instance. It does work on kbin.social but the two instances seem to have possibly different methods to blur as fedio.io also has a little eye icon in the thumbnail. Additionally, the magazine icons for 18+ magazines also seem to be blurred on that instance, which might be a good additional feature request for this function to also unblur them too when enabled (Just search for @lemmynsfw for example in the Magazine search).

I'm not sure if this is a general mbin related issue or specific to this instance.

**To Reproduce**
1. Go to fedia.io
2. Find a 18+ image submission.
3. Enable the auto unblur.
4. See that blurred thumbnails aren't unblurred.

**Expected behavior**
Blurred thumbnails getting unblurred.

**KES version:**
- 3.1.0

**Extension and version:**
- Extension: Violentmonkey
- Version number: 2.17.0

**Desktop (please complete the following information):**
 - OS: Nobara Linux 38
 - Browser Firefox
 - Browser version 121

**Comment by aclist** [comment]
Thanks for the report. fedia.io is using [Mbin](https://github.com/MbinOrg/mbin), a fork of kbin. Some elements might be changed or differ in this version. While many aspects are similar, unfortunately, we can't realistically support diverging implementations of the site, since they could have wildly different elements, tags, and styling, and it would be impossible to maintain over time. KES targets sites running on the stable version of kbin.

Hopefully the different sites will converge around a single framework, but it seems like Mbin has decided to change stylistic elements in addition to the backend. If mbin becomes the de facto standard in the future, we can consider reevaluating this.

**Comment by aclist** [comment]
@NaturalHate

We have decided to make a push for 100% compatibility of all KES add-ons on mbin. The issue with blurred magazine cover images and avatar icons has been fixed in testing, but the issue you mentioned of images being blurred on the thread index is still pending: specifically, is there a way to cause images to be shown on those NSFW magazines? When we search for NSFW magazines on fedia.io and visit any of those magazines, they have no posts, as if they aren't being federated from the home instance. Have you had this issue?

**Comment by NaturalHate** [comment]
@aclist 

>When we search for NSFW magazines on fedia.io and visit any of those magazines, they have no posts, as if they aren't being federated from the home instance. Have you had this issue?

Yes, on kbin and mbin actually.
I typically see always the same few communities from @lemmynsfw pop up and I think it was barely any showing up on kbin. When you Magazine search for the instance (see URL below) then only a few of the many communities show up and a lot of them don't have much if any content inside of them compared to when you visit the actual Lemmy instance. If you try to manually search for, or enter the kbin / mbin URL of a lemmynsfw instance that you know exists and has content, then it even gives you an "empty" or "404 not found" respectively. I don't know where this federation issue comes from though or if it is related to 18+ content or specific instances but I wouldn't be surprised if it is. It's just harder to gauge with the many niche instances that are out there. 

Examples: 
https://fedia.io/magazines?query=flatchested%40lemmynsfw&fields=names&federation=all&adult=show
https://fedia.io/m/flatchested@lemmynsfw.com

> specifically, is there a way to cause images to be shown on those NSFW magazines?

What exactly do you mean by causing images to be shown? I meant the images that aren't actual content submissions, like the logos in the sidebar, or even when you go through the Magazine search. You can manually unblur them by hovering over them.

Examples: 
https://fedia.io/m/boobs@lemmynsfw.com
https://fedia.io/magazines?query=%40lemmynsfw&fields=names&federation=all&adult=show

The instance admin actually gave me a quick Userscript that at least unblurs most of the content images but I've seen some regular non 18+ threads with blurred thumbnails pop up every now and then too. Unsure whether that's related at all or just a bug on their side. I'll post it below in case it is helpful.

```
// ==UserScript==
// @name         Mbin tweak
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  Unhide NSFW entries automatically
// @match        https://fedia.io/*
// @require      https://greasyfork.org/scripts/12228/code/setMutationHandler.js
// ==/UserScript==

checkThem([].slice.call(document.querySelectorAll('input[type="checkbox"].sensitive-state')));

setMutationHandler(document, 'input[type="checkbox"].sensitive-state', checkThem);

function checkThem(nodes) {
    nodes.forEach(function(n) { n.checked = true });
}
```

**Comment by aclist** [comment]
> What exactly do you mean by causing images to be shown? I meant the images that aren't actual content submissions, like the logos in the sidebar, or even when you go through the Magazine search. You can manually unblur them by hovering over them.

Magazine logos and circular avatars being blurred is fixed in the upcoming version. I'm referring to the actual content images that the script you provided is supposed to unblur: I'm not actually seeing any content images whatsoever in any of the magazines (checked all of them), except for SFW celebrity photos magazines. No thumbnail, no eye icon, no posts, even. I'm wondering if there is some setting at the user-level that is blocking NSFW content from being loaded in the first place. I searched high and low for a setting in the sidebar, but did not find anything. This is also happening when logged out.

The images only seem to load when going to the home instance.

To clarify, I'm using the below terminology:

- Magazine logo: logo for the magazine, appears in the sidebar, is sometimes blurred if NSFW. This is going to be fixed
- Circular avatar: a circular avatar representing the magazine, appears in the magazine search index, is sometimes blurred if NSFW. This is going to be fixed
- Content image/thumbnail: images appearing in the thread index of a magazine or inside of posts

Also tried subscribing to different magazines to see if the content images are for subscribers only, but that didn't work, either. Strangely, many of the magazines in the thread index list 0 posts, but even the ones that list a handful of posts have no content. For example, the `porn@lemmynsfw` lists 10 posts on the magazine search, but there are none shown in the thread index. (Only 10 microblogs.) Strangely, clicking onto microblogs also shows no content.

Is this happening for you as well?

**Comment by NaturalHate** [comment]
> I'm not actually seeing any content images whatsoever in any of the magazines (checked all of them), except for SFW celebrity photos magazines. No thumbnail, no eye icon, no posts, even. I'm wondering if there is some setting at the user-level that is blocking NSFW content from being loaded in the first place. 

Oh, it's the same as on kbin. Just uncheck "Hide NSFW content".
https://fedia.io/settings/general

> For example, the porn@lemmynsfw lists 10 posts on the magazine search, but there are none shown in the thread index. (Only 10 microblogs.) Strangely, clicking onto microblogs also shows no content.
> 
> Is this happening for you as well?

It lists only 10 posts on the magazine search for me too but the community a lot more than that when I enter it. I never found the stats on the magazine search page to be overly useful unfortunately. One of the many negative quirks about kbin / mbin which I hoped get fixed quicker.

**Comment by aclist** [comment]
> Oh, it's the same as on kbin. Just uncheck "Hide NSFW content".

OK, great, this is easy to fix now. Will get started working on it for inclusion in #260.
