### ISSUE TITLE
[BUG] Atomic mods should not propagate on page load if already off

### ISSUE THREAD

**Issue by NonITExpert** [aclist/kbin-kes#249]
**Is your feature request related to a problem? Please describe.**
When KES is enabled, Mbin logo goes away and changes to "Homepage". Navbar>Toggle Logo is off. Please refer to screenshot attached. The only icon choices are 'hidden', Kbin no text, Kbin with text, Kibby.

**Describe the solution you'd like**
Add an option to Navbar>Toggle Logo for user to selectMbin icon

**Describe alternatives you've considered**
![Screenshot_20240205_105959_Firefox Nightly](https://github.com/aclist/kbin-kes/assets/138516886/365e4d5a-764d-4995-b1e8-d08fc34cd41d)

**Comment by Pamasich** [comment]
I don't think KES is currently meant to support mbin. The only mbin instance listed in the userscript's `@match` list is fedia.io, which was probably added back when it was a kbin instance.

So you'll probably run into more incompatibilities with other features where mbin has made changes.

---

At a glance, it seems like the issue here is that KES runs the main function of each add-on when the page loads, whether or not they are turned on or off. Inside that main function, logic then decides to set up or undo the add-on.

The undo function of this particular add-on removes the existing logo and attempts to load the original one of the instance via `https://kbin.melroy.org/kbin_logo.svg `. A path which doesn't exist on mbin instances (it's `/mbin_logo.svg` instead).  
So what happens is that the mbin logo gets removed, but KES fails to load the default logo from the instance, so you only get a broken image like that.

@aclist Is it possible to not call the add-ons on page load if they are turned off (the parameter is false)? I think that would make more sense then the current behavior of restoring the original site to... its original state. That just sounds like unnecessary work being done.

**Comment by aclist** [comment]
This is partially a duplicate of #239 in that KES targets kbin. Mbin, being a fork of kbin, has decided to change the IDs and names of elements on pages, so in trying to add support for mbin, we would be breaking support for kbin, or vice versa. Or, if adding support for both, we would be doubling the complexity in trying to target both sites and their different taxonomy of elements. If mbin becomes the de facto standard in the future, we could look at refactoring everything to support that, but for the time being KES targets kbin instances (for better or worse).

@Pamasich To the first point, it seems like a good idea. To the second point, it was originally done in order to allow hot-swapping the state of add-ons without reloading a given page. But yes, it seems reasonable and feasible to skip loading that add-on altogether if we are navigating to a new page.

While this will not fix compatibility with every add-on, it is a good security fix in general.

**Comment by NonITExpert** [comment]
Thanks for responding. I understand the the dust is still settling on the Mbin/Kbin split. What I like about KES is that most addons work well with both Kbin and Mbin. The problem with the Toggle Logo addon however, is that when it's turned off, KES appears to overwrite the original instance Logo icon in that space and replace it with the word "Homepage". Please refer to my original screenshot. I'd like to see the instance logo remain **_as-is_** when the addon is **not** enabled. Can that be fixed?

**Comment by aclist** [comment]
> Thanks for responding. I understand the the dust is still settling on the Mbin/Kbin split. What I like about KES is that most addons work well with both Kbin and Mbin. The problem with the Toggle Logo addon however, is that when it's turned off, KES appears to overwrite the original instance Logo icon in that space and replace it with the word "Homepage". Please refer to my original screenshot. I'd like to see the instance logo remain **_as-is_** when the addon is **not** enabled. Can that be fixed?

Yes, I have made some changes to my local version to fix this, and confirm that it is working as intended now. I will be incorporating those changes into the 3.3.0 milestone, if not sooner.

**Comment by NonITExpert** [comment]
So far, (knock on wood) KES works well with mbin 🤞🏽 My only issue is the logo bug. In my mind I see Mbin as fork of kbin.

**Comment by NonITExpert** [comment]
One more thing, KES seems to work fine with Mbin when you add "https://kbin.melroy.org//*" to User Matches in KES Settings using Tampermonkey

**Comment by aclist** [comment]
Resolved by 75e87c1411de1adb73c43f97ef7d31906fc285de

I've decided to fast-track this into a hotfix (3.2.4) instead of waiting for the next feature release. The fix is live on the testing branch and will make its way into the stable branch within 24 hours.

**Comment by aclist** [comment]
@NonITExpert 

## A few updates:
- Since posting the last message, I haven't been able to connect to kbin (some connectivity issues are ongoing, it seems), so held off on releasing the hotfix in the originally stated 24 hours. As of this writing, the site is not working.
- Meanwhile, v3.3.0 is already finished, so I've consolidated this fix and other changes into that version. As soon as kbin is back online, I will release that version.

## What was fixed:
- If an add-on is not expicitly turned on, KES will not try to perform additional setup steps for that add-on, which will prevent erroneous behavior if the add-on is not properly supported (e.g. on Mbin).
- Contrary to my original comments, I decided to go ahead and fix the Toggle Logo add-on to also support Mbin, since the fix was fairly simple. So now you can toggle this add-on on or off on both Kbin and Mbin instances and it will behave as expected. (More on this below)

## Future progress
- It looks like popular sentiment is shifting from Kbin to Mbin due to the more frequent update cadence, so it seems like a real possibility that Mbin could become the software of choice for many instances. In light of this, I think we should make a concerted effort to support both flavors and refactor add-ons that exhibit problems with Mbin.
- For now, no explicit guarantee of functionality is being made for Mbin, but if you encounter problems with other add-ons, please report them, and I will fix them. I think we can lay the groundwork for compatibility in the future, which should prepare us if users decide to migrate en masse. The vast majority of add-ons are working. In the future we can consider whether KES itself needs to be renamed to reflect this updated scope.
