### ISSUE TITLE
[BUG] The notification panel mod sometimes causes dropdowns to appear unstyled

### ISSUE THREAD

**Issue by Pamasich** [aclist/kbin-kes#251]
**Describe the bug**
As explored [in this issue](https://github.com/Pamasich/kbin-kes/issues/62) on my development repository, the  notification panel mod sometimes injects a style that causes all dropdowns to appear unstyled.

This looks like this:
![image](https://github.com/aclist/kbin-kes/assets/18553452/e4e84a39-68e3-43f0-a3b6-25c19dc2714a)
![image](https://github.com/aclist/kbin-kes/assets/18553452/2ea28a54-266a-485a-a4fe-6bad581c84d9)

The style causing this is the following:
![image](https://github.com/aclist/kbin-kes/assets/18553452/1412c399-1198-483f-b433-a55f5c9cacc1)

Removing the padding line in particular seems to fix the issue I'm seeing.

I'm not sure what this style is meant to do and under what conditions it is applied (it seems random to me as a user), but I think it needs to be refactored so it doesn't apply to all dropdowns.

**Comment by aclist** [comment]
This should be provisionally fixed, but I couldn't find a reliable way of reproing this bug in terms of making the broken style appear on other dropdowns. In theory, the style was supposed to be wiped when the notifications panel was closed, so I couldn't figure out how it was applying to dropdowns that can only be opened when the noti panel is closed (since the panel is a modal and prevents clicking on other things onscreen until it is destroyed).
