### ISSUE TITLE
[CHORE] Potential future rate limit problem

### ISSUE THREAD

**Issue by Pamasich** [aclist/kbin-kes#253]
> I think eventually this is going to bump into the rate limit if the number of mods exceeds about 80 (currently at about half that). Maybe we should be thinking about keeping atomic scripts as files-of-reference in the source code and accepting atomic scripts for PRs, but having a build routine that consolidates all of them into a single JS file from which the functions can be sourced at runtime. (At this point, functions would absolutely have to be private to each mod to prevent collisions, and any mods not following this would need to be refactored. Or some sort of mod function namespacing logic could be used.) This would effectively shrink the requires from N=mods to 1, plus a handful of files like the CSS. 

 _Originally posted by @aclist in [pamasich/kbin-kes#44](https://github.com/Pamasich/kbin-kes/issues/44#issuecomment-1985888605)_

Reposting this here so it stays on the radar.

I think adding all the mods to a single file would also help with [the greasyfork idea.](https://github.com/aclist/kbin-kes/issues/132)

---

> At this point, functions would absolutely have to be private to each mod to prevent collisions, and any mods not following this would need to be refactored. Or some sort of mod function namespacing logic could be used.

Isn't this already the case though? If I look at KES in the dev tools, it's all just one long file with all the mods and KES and any other dependencies. I think whether we have the browser/monkey do it or do it manually, the end result should be the same in that regard. In other words, I don't think this would introduce any limitations that aren't already present.

**Comment by Pamasich** [comment]
Created a matching issue on my repository too, but I don't know bash scripting (I use windows), so this doesn't mean I'm volunteering to do this. Just remarking it there so I remember this is something that needs to be done.

**Comment by aclist** [comment]
> I think adding all the mods to a single file would also help with https://github.com/aclist/kbin-kes/issues/132

Yes, this makes sense.

> Isn't this already the case though? If I look at KES in the dev tools, it's all just one long file with all the mods and KES and any other dependencies. I think whether we have the browser/monkey do it or do it manually, the end result should be the same in that regard. In other words, I don't think this would introduce any limitations that aren't already present.

Correct, the end result is the same, but it affects the build process: currently private/namespaced functions are treated as a recommendation that may produce undefined behavior if it is not followed. The build process just updates kes.user.js with the remote URLs and lets them be loaded when KES is actually instantiated--so any collisions between functions across mods would only be revealed at runtime.

But if everything gets merged into one script during the build process, if there are name collisions, it is not going to pass acceptance tests/linting, because the names of colliding functions would all be known at "compile" time and reside in a single script.

**Comment by aclist** [comment]
Resolved by #255

**Comment by aclist** [comment]
> but I don't know bash scripting (I use windows)

Technically, the new combined `funcs.js` makes it easier to prototype local changes, since you just need to change a single `@requires` line in the header and not dig through and find the correct URL of the remote resource. But to do so, you have to generate the new `funcs.js` with the shell script. Can you run scripts through WSL?

**Comment by Pamasich** [comment]
> > but I don't know bash scripting (I use windows)
> 
> Technically, the new combined `funcs.js` makes it easier to prototype local changes, since you just need to change a single `@requires` line in the header and not dig through and find the correct URL of the remote resource. But to do so, you have to generate the new `funcs.js` with the shell script. Can you run scripts through WSL?

I think I've read Git for windows comes with bash included, so I think it should work even without WSL? But yeah, I'll have to look into that.

**Comment by aclist** [comment]
Alright, FYI, the script is not super parametric at the moment and is "dumb": it is kicked off by pre-commit hooks, so expects the current working directory to be the root of the repo (invocation as `./build/scripts/concat_funcs`), and will place the new funcs file in `/helpers/funcs.js`, so invocation from anywhere else will set the wrong paths.
