### ISSUE TITLE
[BUG] KES doesn't load in Userscripts for Safari on iOS

### ISSUE THREAD

**Issue by artillect** [aclist/kbin-kes#74]
**Describe the bug**
Same as #63, settings icon doesn't appear because of (presumably) a syntax error.

**To Reproduce**
1. Install Userscripts for Safari
2. Open kbin
3. ???
4. Profit

**Expected behavior**
The settings button should appear and KES should load properly

**Screenshots**

**KES version:**
- 1.1.3

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: iOS
 - Browser: Safari
 - Version: Unknown

**Additional context**
The fix for this seems to be to undo the fix for #63. Userscripts doesn't support the `GM_` API functions, only the `GM.` ones. Not sure how to go about this, we could check `GM.info` to get the user's script manager and then use the appropriate function given that information

**Comment by Oricul** [comment]
The problem with GM.info and GM_info is that when one works, the other doesn't. TamperMonkey tends to be the most widely used and should probably be the de-facto source for when choosing what to support.

That said, what's stopping us from granting both, testing with an if statement and use whichever works?

**Comment by aclist** [comment]
> The problem with GM.info and GM_info is that when one works, the other doesn't. TamperMonkey tends to be the most widely used and should probably be the de-facto source for when choosing what to support.

It was targeted against TM, but looks like all bets are off when you have scenarios like someone installing some alternate GM fork on their Mac on a phone. I don't know how many people are using mobile on kbin, but it seems like a non-trivial number.

> That said, what's stopping us from granting both, testing with an if statement and use whichever works?

It's just crazy enough to work

> Not sure how to go about this, we could check GM.info to get the user's script manager and then use the appropriate function given that information

Provided `GM.info.scriptHandler` is also supported in this Userscripts thing, it seems straightforward enough. So first we need to test both GM_info and GM.info, find a valid identifier, and then take it from there. Could probably also have an internal function called `safeGM()` or something that scripts can call if they need access to GM_/. commands and we give them the right result back?

**Comment by aclist** [comment]
Looking into it, it is not enough to just test scriptHandler or test GM_* or GM.* for validity, because the implementation of some of these GM functions differs. For example:

GM.getValue -> returns promise
GM_getValue -> returns string

This affects the handling of the resulting value, so if a mod is calling GM.getValue and expecting one thing but getting another after we interpolate it to the right GM type, it ain't gonna work out of the box.

The other thing to do would be maintain concurrent versions for different OSes/systems

**Comment by aclist** [comment]
Basic prototype with two arguments

```
    let gmPrefix
    try {
        if(GM_info){
            gmPrefix = "GM_"
        } else {
            gmPrefix = "GM."
        }
    } catch {
        console.log(error);
    }

    window.safeGM = function(func,arg1,arg2){
        let use
        let underscore = {
            setValue(arg1,arg2) { return GM_setValue(arg1,arg2) },
            getValue(arg1,arg2) { return GM_getValue(arg1) }
        }
        let dot = {
            setValue(arg1,arg2) { GM.setValue(arg1,arg2) },
            getValue(arg1,arg2) { GM.getValue(arg1) }
        }
        if (gmPrefix === "GM_") {
            use = underscore
        } else {
            use = dot
        }
        return use[func](arg1,arg2);
    }
    let mykey = "foo"
    let myval = "bar"
    safeGM("setValue",mykey,myval);
    console.log("normal method");
    console.log(GM_getValue(mykey));
    console.log("safeGM method");
    console.log(safeGM("getValue",mykey));
```

**Comment by aclist** [comment]
Proposed patch fix is at: https://github.com/aclist/kbin-kes/pull/81

It contains a lengthy commit message here: https://github.com/aclist/kbin-kes/pull/81/commits/493c4d4e96e62b62bb27262189ee9a4634ebefb8

Need help testing on different browser/extension combinations.

**Comment by aclist** [comment]
@artillect  @Oricul 

I don't have an iOS test bench, perhaps one of you does?

**Comment by Oricul** [comment]
> I don't have an iOS test bench, perhaps one of you does?

Sorry, I do not have iOS anything.

>     1. https://www.greasespot.net/2017/09/greasemonkey-4-for-script-authors.html
> And the smoking gun:
> 
> > As of today, there is no support for: GM_log (use console.log), **GM_addStyle** [my bold], GM_registerMenuCommand, nor GM_getResourceText.

Oop! You edited before I could respond. But yes, we can simply watch for that in safeGM. We already account for determining their GM prefix, so within that prefix, just check if **<prefix>addStyle** exists, and if not, revert to doing it manually as you suggest.

**Comment by aclist** [comment]
> Sorry, I do not have iOS anything.

Me, neither. But the problem seems more generalized to the GM API, at least.

> Oop! You edited before I could respond. But yes, we can simply watch for that in safeGM. We already account for determining their GM prefix, so within that prefix, just check if addStyle exists, and if not, revert to doing it manually as you suggest.

It looks like the polyfill script is essentially accounting for the fact that the dot API returns promises and handling that, and it looks like it also reimplements as native functions the xmlHttpRequest, getResourceText, etc., using the `fetch` API. But unless I'm missing something, as of this writing, these APIs are already available in both flavors, and it's just a semantic issue with the API prefix.

I already implemented the async when using getValue/setValue, so we could just extend that when necessary. It looks like most scripts aren't really deeply using the GM API besides a few things, so seems like we can probably hotfix this with what he have and look to adapting the polyfill if and when that becomes necessary.

Apropos of async, there is still a bit of tech-debt being carried around in kes.user.js in that there isn't additional error handling for the rare scenario where, e.g., GitHub is down and the resources can't be obtained, so the menu is going to be blank and needs some kind of error message ("Remote resources could not be fetched, please reload and try again").

> We already account for determining their GM prefix, so within that prefix, just check if addStyle exists, and if not, revert to doing it manually as you suggest.

That seems reasonable. I think the main one being leveraged by mods is addStyle.

**Comment by aclist** [comment]
OK, I spent WAY too long on this, but after much hand-wringing and jumping through the vagaries of GM's async-everything implementation, I think I have a version that works on all variants. Had to create a custom function to insert CSS and, since the GM API dropped support for getResourceText, had to resort to getting resources directly from their URLs instead of assigning them to a named resource (not a big deal).

It seems to be the same on all versions, though I noticed some potential CSS oddities that need to be looked at. I'll make a patch for it when I'm back at the desk.

**Comment by aclist** [comment]
To reduce the possibility of collisions and false positives, I want to release the safeGM fix into the stable branch without pulling in too many other new mods or features, so we can get confirmation from the GM and iOS users. Over here, it is working on all variants, but still have to test iOS. 

If someone else wouldn't mind testing the other extensions for a sanity check, that would be good. We can also wait until @artillect is back and target this for next week.

**Comment by aclist** [comment]
Confirmed working on Userscripts
