### ISSUE TITLE
[BUG] Compatibility with Hermit

### ISSUE THREAD

**Issue by JasonMaloney** [aclist/kbin-kes#83]
**Describe the bug**
[Hermit](https://hermit.chimbori.com/) offers the ability to convert any website into a so-called "Lite App" (similar to a PWA) using Android System WebView. It has built-in support for userscripts; but for security and privacy reasons, its implementation disallows certain features.

Due to lack of support for `@grant`, `@require`, and `@resource`, KES fails to load.

**To Reproduce**
1. Create a Lite App for kbin.social.
2. Attempt to install KES using typical installation method.
3. Observe warning message (see below).

**KES version:**
- 1.2.0

**Smartphone (please complete the following information):**
 - Device: Pixel 6a
 - OS: 13 (TQ3A.230705.001.A1)
 - Browser: Hermit
 - Version: 25.0.2

**Additional context**
Warning message observed upon installation:
> For security & privacy reasons, scripts cannot import external code. The following tags are not supported: `@grant`, `@require`, `@resource`. Learn more about alternatives. [Learn More](https://hermit.chimbori.com/features/userscripts)

**Comment by aclist** [comment]
Inherent to its design, KES relies on loading external resources such as the layout of the UI pages and the script list manifest to "populate" the menu, rather than hardcoding all of these settings internally. This is integral to the declarative framework that allows the layout and content to be isolated from the business logic of the code.

Also, many of the individual scripts in KES make modifications to the page style through calls to, e.g., GM_addStyle, which allows for inserting CSS into the page, or rely on resources like jQuery, served via a CDN. I suspect that these scripts would also individually fail to run on Hermit if it enforces this strict policy.

To ameliorate the above, Hermit suggests bundling all of the scripts into a single file and structurally rewriting the framework into something more "app"-like, including bundling resources like jQuery. This seems like quite a drastic structural and conceptual rewrite, and would necessarily introduce a lot of overhead and complexity for the small benefit of supporting mobile phones, and would in turn pull in a lot of technical dependencies that desktop users probably don't need.

It seems like this use case would be better served by a standalone app to interact with kbin, rather than *monkey family scripts, which are originally intended for desktop use. I feel that anything involving bootstrapping what is here into a pseudo web-app is highly experimental and frought with problems. Alternatively, using an app with more permissive settings.

I'm considering this WONTFIX, but maybe one of the other contributors has an alternative suggestion or insight they want to make here.

**Comment by Oricul** [comment]
There are some options around moving the `@resource` tags, even while keeping them in separate js files, but overall I think it adds undue complexity. The **[gm4-polyfill](https://github.com/greasemonkey/gm4-polyfill)** point may actually be a good alternative to https://github.com/aclist/kbin-kes/issues/74 - but it would need some thorough testing.

As for packing, I think that's going a bit too far - at least at this stage.
